#!/usr/bin/env node

/**
 * Firebase Initialization Helper Script
 * Run this to set up your Firebase project quickly
 */

const readline = require('readline');
const fs = require('fs');
const path = require('path');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

console.log('🔥 Firebase Setup Helper for WAEC Practice PWA');
console.log('===================================================\n');

async function promptUser(question) {
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      resolve(answer.trim());
    });
  });
}

async function setupFirebase() {
  console.log('📝 Please provide your Firebase configuration:');
  console.log('   (Get these from Firebase Console > Project Settings > Web App)\n');

  const config = {
    apiKey: await promptUser('🔑 API Key: '),
    authDomain: await promptUser('🌐 Auth Domain (project-id.firebaseapp.com): '),
    projectId: await promptUser('📁 Project ID: '),
    storageBucket: await promptUser('🗂️  Storage Bucket (project-id.appspot.com): '),
    messagingSenderId: await promptUser('📨 Messaging Sender ID: '),
    appId: await promptUser('📱 App ID: '),
    measurementId: await promptUser('📊 Measurement ID (optional): ')
  };

  // Validate required fields
  const requiredFields = ['apiKey', 'authDomain', 'projectId', 'storageBucket', 'messagingSenderId', 'appId'];
  const missingFields = requiredFields.filter(field => !config[field]);

  if (missingFields.length > 0) {
    console.log(`\n❌ Missing required fields: ${missingFields.join(', ')}`);
    console.log('Please run the script again with complete information.');
    rl.close();
    return;
  }

  // Create .env file
  const envContent = `# Firebase Configuration - Generated by firebase-init.js
# NEVER commit this file to version control!

FIREBASE_API_KEY=${config.apiKey}
FIREBASE_AUTH_DOMAIN=${config.authDomain}
FIREBASE_PROJECT_ID=${config.projectId}
FIREBASE_STORAGE_BUCKET=${config.storageBucket}
FIREBASE_MESSAGING_SENDER_ID=${config.messagingSenderId}
FIREBASE_APP_ID=${config.appId}
FIREBASE_MEASUREMENT_ID=${config.measurementId || ''}

# Environment
NODE_ENV=development

# Generated on: ${new Date().toISOString()}
`;

  try {
    fs.writeFileSync('.env', envContent);
    console.log('\n✅ Created .env file successfully!');
  } catch (error) {
    console.log('\n❌ Error creating .env file:', error.message);
    rl.close();
    return;
  }

  // Update firebase-config.js with actual values
  const configFilePath = path.join('js', 'firebase-config.js');
  
  try {
    let configFile = fs.readFileSync(configFilePath, 'utf8');
    
    // Replace the config object
    const newConfigSection = `const firebaseConfig = {
  apiKey: "${config.apiKey}",
  authDomain: "${config.authDomain}",
  projectId: "${config.projectId}",
  storageBucket: "${config.storageBucket}",
  messagingSenderId: "${config.messagingSenderId}",
  appId: "${config.appId}"${config.measurementId ? `,
  measurementId: "${config.measurementId}"` : ''}
};`;

    configFile = configFile.replace(
      /const firebaseConfig = \{[\s\S]*?\};/,
      newConfigSection
    );

    fs.writeFileSync(configFilePath, configFile);
    console.log('✅ Updated firebase-config.js successfully!');
  } catch (error) {
    console.log('❌ Error updating firebase-config.js:', error.message);
  }

  console.log('\n🎉 Firebase configuration complete!');
  console.log('\nNext steps:');
  console.log('1. 📋 Copy firestore.rules to Firebase Console > Firestore > Rules');
  console.log('2. 🔐 Enable Authentication (Anonymous + Email/Password)');
  console.log('3. 🌐 Add authorized domains in Firebase Console');
  console.log('4. 🚀 Deploy your app!');
  console.log('\nSee FIREBASE_DEPLOYMENT.md for detailed instructions.');

  rl.close();
}

// Run the setup
setupFirebase().catch(console.error);